[package]
name = "imgsize"
version = "0.1.0"
edition = "2021"

[dependencies]
fast_image_resize = {version = "4.0.0", features = ["image"]}
fl2rust-macro = "0.5.19"
fltk = "1.4.31"
glob = "0.3.1"
image = "0.25.1"
