[package]
name = "imgsize"
version = "0.6.0"
edition = "2021"
rust-version = "1.81.0"

[dependencies]
crossbeam = "0.8.4"
fast_image_resize = {version = "5", features = ["image"]}
iced = { version = "0.12", features = ["smol", "tokio"] }
image = "0.25"
log = { version = "0.4.26", features = ["kv"] }
native-dialog = "0.7"
structopt = "0.3.26"
structured-logger = "1.0.3"
testdir = "0.9.3"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
strip = true
lto = true
panic = "abort"
