[package]
name = "imgsize"
version = "0.5.0"
edition = "2021"
rust-version = "1.81.0"

[dependencies]
crossbeam = "0.8.4"
fast_image_resize = {version = "5", features = ["image"]}
glob = "0.3"
iced = { version = "0.12", features = ["smol", "tokio"] }
image = "0.25"
native-dialog = "0.7"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
strip = true
lto = true
panic = "abort"
